### ISSUE TITLE
Hub crash whenever network is down

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#137]
Hub crash whenever the network is down, on boot or while it is running

Error from the log

``` dart

Unhandled exception:
SocketException: Failed host lookup: 'px1.tuyaeu.com' (OS Error: Temporary failure in name resolution, errno = -3)
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1808:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:237:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:60:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2437:24)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2808:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2813:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2697:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2569:7)
#10     IOClient.send (package:http/src/io_client.dart:35:38)
#11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
#12     BaseClient.post (package:http/src/base_client.dart:32:7)
#13     post.<anonymous closure> (package:http/http.dart:69:16)
#14     _withClient (package:http/http.dart:164:20)
#15     post (package:http/http.dart:68:5)
#16     CloudTuya.consistentRequest (package:cbj_hub/infrastructure/devices/tuya_smart/tuya_smart_remote_api/cloudtuya.dart:178:37)
#17     CloudTuya.login (package:cbj_hub/infrastructure/devices/tuya_smart/tuya_smart_remote_api/cloudtuya.dart:63:15)
#18     TuyaSmartConnectorConjector.accountLogin (package:cbj_hub/infrastructure/devices/tuya_smart/tuya_smart_connector_conjector.dart:34:49)
#19     CompanysConnectorConjector.setVendorLoginCredentials (package:cbj_hub/infrastructure/devices/companys_connector_conjector.dart:119:12)
#20     HiveRepository.loadFromDb.<anonymous closure> (package:cbj_hub/infrastructure/local_db/local_db_repository.dart:65:34)
#21     Right.fold (package:dartz/src/either.dart:200:64)
#22     HiveRepository.loadFromDb (package:cbj_hub/infrastructure/local_db/local_db_repository.dart:64:10)
<asynchronous suspension>

Process finished with exit code 255

```

**Comment by guyluz11** [comment]
Done
