### ISSUE TITLE
Snap crash when started with device

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#150]
Snap crash when started with device

Log:

```
user:~$ sudo snap logs cbj-hub  -n 50
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: │ 00:09:21.066 (+0:00:00.319403)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: │ 💡 Scenes got saved to local storage
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: │ 00:09:21.103 (+0:00:00.356716)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: │ 💡 Devices got saved to local storage
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: │ 00:09:21.117 (+0:00:00.370342)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: │ 💡 Devices got saved to local storage
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: │ 00:09:21.128 (+0:00:00.381325)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: │ 💡 Devices got saved to local storage
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: Unhandled exception:
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 55164
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1808)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #3      Socket._startConnect (dart:io-patch/socket_patch.dart:2027)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #4      Socket.startConnect (dart:io/socket.dart:784)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2808)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2813)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2697)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2569)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #10     IOClient.send (package:http/src/io_client.dart:35)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #12     BaseClient.post (package:http/src/base_client.dart:32)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #13     post.<anonymous closure> (package:http/http.dart:69)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #14     _withClient (package:http/http.dart:164)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #15     post (package:http/http.dart:68)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #16     NodeRedAPI.postFlow (package:cbj_hub/infrastructure/node_red/node_red_api/node_red_api.dart:142)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #17     NodeRedRepository.createNewNodeRedScene (package:cbj_hub/infrastructure/node_red/node_red_repository.dart:25)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: #18     SceneCbjRepository.addNewScene (package:cbj_hub/infrastructure/scenes/scene_repository.dart:72)
2022-06-02T00:09:21+03:00 cbj-hub.cbj-hub[2229]: <asynchronous suspension>
2022-06-02T00:09:21+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Main process exited, code=exited, status=255/EXCEPTION
2022-06-02T00:09:21+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-06-02T00:09:21+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Scheduled restart job, restart counter is at 11.
2022-06-02T00:09:21+03:00 systemd[1]: Stopped Service for snap application cbj-hub.cbj-hub.
2022-06-02T00:09:21+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Start request repeated too quickly.
2022-06-02T00:09:21+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-06-02T00:09:21+03:00 systemd[1]: Failed to start Service for snap application cbj-hub.cbj-hub.

```

**Comment by guyluz11** [comment]
Done
