### ISSUE TITLE
Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#153]
Crash from gRPC package.

1. Start the server.
2. Open the app on the phone.
3. Disconnect phone to WiFi and reconnect it after 5 seconds.

Log from hub:

``` dart
Unhandled exception:
Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:595:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:867:13)
#2      TransportStream.sendHeaders (package:http2/transport.dart:147:22)
#3      ServerHandler_.sendTrailers (package:grpc/src/server/handler.dart:361:13)
#4      ServerHandler_._sendError (package:grpc/src/server/handler.dart:410:5)
#5      ServerHandler_._onResponse (package:grpc/src/server/handler.dart:287:7)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

Tried to put try catch around that line and it fixed the crash
https://github.com/grpc/grpc-dart/blob/94b71a3e1cbfae366ead2d67f1b30fd03b8d4ee2/lib/src/server/handler.dart#L361

Created issue in gRPC package and opened [this repo](https://github.com/guyluz11/grpc_bug_reproduce) in order to reproduce it in a clean environment.

**Comment by guyluz11** [comment]
Found that it coming from here
https://github.com/CyBear-Jinni/cbj_hub/blob/06accdfb9edf94904c8cdaebc6710f07df8e1189/lib/infrastructure/app_communication/app_communication_repository.dart#L365

**Comment by guyluz11** [comment]
Pull request got marged, will close the issue now
