### ISSUE TITLE
Exception Stream has already been listened to

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#162]
```dart
Unhandled exception:
Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:1028:33)
#4      _StreamIterator.moveNext (dart:async/stream_impl.dart:1004:12)
#5      CompaniesConnectorConjector.searchPingableDevicesAndSetThemUpByHostName (package:cbj_hub/infrastructure/devices/companies_connector_conjector.dart)
<asynchronous suspension>
```

**Comment by guyluz11** [comment]
Closing as can't reproduce
