### ISSUE TITLE
Hub crash if started without any network

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#168]
1. Disconnect Hub computer from all networks.
2. Run the Hub code.

```dart
Unhandled exception:
SocketException: Send failed (OS Error: Network is unreachable, errno = 101), address = 0.0.0.0, port = 5353
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2450:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MdnsScanner._findingMdnsWithAddress (package:network_tools/src/mdns_scanner/mdns_scanner.dart:71:54)
<asynchronous suspension>
#4      MdnsScanner.searchMdnsDevices (package:network_tools/src/mdns_scanner/mdns_scanner.dart:41:29)
<asynchronous suspension>
#5      CompaniesConnectorConjector.searchAllMdnsDevicesAndSetThemUp (package:cbj_hub/infrastructure/devices/companies_connector_conjector.dart:144:43)
<asynchronous suspension>
```

**Comment by guyluz11** [comment]
Created issue for that in [network_tools](https://github.com/git-elliot/network_tools/issues/60)

**Comment by guyluz11** [comment]
Merged, done
