### ISSUE TITLE
Hive local db error

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#248]
```dart
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: │ 22:33:20.966 (+0:00:00.225169)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: │ ⛔ Local DB hive error while getting rooms: HiveError: Cannot read, unknown typeId: 35. Did you forget to register an adapter?
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: Unhandled exception:
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: HiveError: Cannot read, unknown typeId: 35. Did you forget to register an adapter?
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:325)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: #1      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: #2      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: #3      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: <asynchronous suspension>
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: #4      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: <asynchronous suspension>
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: #5      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: <asynchronous suspension>
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: #6      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: <asynchronous suspension>
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: #7      HiveRepository.getRoomsFromDb (package:cbj_hub/infrastructure/local_db/local_db_hive_repository.dart:188)
2022-11-01T22:33:20+02:00 cbj-hub.cbj-hub[21316]: <asynchronous suspension>
2022-11-01T22:33:21+02:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Main process exited, code=exited, status=255/EXCEPTION
2022-11-01T22:33:21+02:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-11-01T22:33:21+02:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Scheduled restart job, restart counter is at 1.
2022-11-01T22:33:21+02:00 systemd[1]: Stopped Service for snap application cbj-hub.cbj-hub.
2022-11-01T22:33:21+02:00 systemd[1]: Started Service for snap application cbj-hub.cbj-hub.

```

**Comment by guyluz11** [comment]
I think it got fixed with some changes that I did.

Closing it.
