### ISSUE TITLE
Too many open files error

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#274]
After running the hub for several hours on my arm device I got this exception.

```dart
Unhandled exception:
SocketException: Failed to create datagram socket (OS Error: Too many open files, errno = 24), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#2      MdnsScanner._findingMdnsWithAddress (package:network_tools/src/mdns_scanner/mdns_scanner.dart:72:5)

```

I think increasing the delay between mdns searches will fix that.

**Comment by guyluz11** [comment]
Changing the delay to 2m didn't fix the problem.

**Comment by guyluz11** [comment]
Opened issue in flutter repo 
https://github.com/flutter/flutter/issues/116528
